dao.rol=com.ipartek.formacion.ejemplos.ipartube.daos.jpa.DaoRolJpa
dao.usuario=com.ipartek.formacion.ejemplos.ipartube.daos.jpa.DaoUsuarioJpa
dao.video=com.ipartek.formacion.ejemplos.ipartube.daos.jpa.DaoVideoJpa
dao.comentario=com.ipartek.formacion.ejemplos.ipartube.daos.jpa.DaoComentarioJpa

negocio.publico=com.ipartek.formacion.ejemplos.ipartube.logicanegocio.impl.PublicoNegocioImpl
